name: Check Script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:

    - name: Installing Dependencies
      run: apt install curl
    
    - name: Checking Installer 
      run: bash curl -s (https://raw.githubusercontent.com/ma4z/Helaport-Installer/main/install.sh)

